### ISSUE TITLE
Change Name of Resource on Selection Screen

### ISSUE THREAD

**Issue by abycurley** [WycliffeAssociates/DOC#114]
Change "Translation Helps" to " Translation Notes"

**Comment by linearcombination** [comment]
This comes from the content source itself and something called translations.json. I will work with the proper upstream person to have them adjust this upstream. Almost everything you see in a generated document comes from the content itself. I'll keep you posted when this gets fixed upstream at WA. 

@PurpleGuitar, here is what it shows in translations.json:

        "code": "tn-wa",
        "name": "ULB Translation Helps",

@PurpleGuitar, could you please change this to 'Translation Notes'. Thx!

**Comment by linearcombination** [comment]
I can accomodate this. I looked again and English is a special case. It is indeed 'ULB Translation Helps' in translations.json as mentioned above, however, currently due to some issues with English only data in translations.json we get the English data from a hardcoded source. This means that I can accommodate this currently. Sorry @PurpleGuitar, eventually we may need to update this in upstream that translations.json pulls from, but currently we are ok.

**Comment by markalolo** [comment]
This is resolved, thanks!
