### ISSUE TITLE
Overlapping text in Khmer TN

### ISSUE THREAD

**Issue by abycurley** [WycliffeAssociates/DOC#163]
extension://efaidnbmnnnibpcajpcglclefindmkaj/https://doc-files.bibleineverylanguage.org/km-tn-eph_km-ulb-eph_lbo_1c_chapter_ltwt.pdf

**Comment by linearcombination** [comment]
@abycurley It looks like the Khmer language can have incredibly long words compared to other languages. Is that correct? This makes for a tricky situation since words aren't normally broken up at end of line.

**Comment by linearcombination** [comment]
@abycurley Never mind, it is only PDF that is having issues with Khmer. HTML, ePub, and Docx are fine so it must be a limitation of the 3rd party library that does the HTML to PDF conversion. Would it be ok if, for now at least, I modify the system so that when Khmer is chosen then the PDF option will not be given, only ePub and Docx? A PDF can be created from the Docx from within Word.

**Comment by abycurley** [comment]
Yes, I think that's a good solution for now.

**Comment by linearcombination** [comment]
A little more info: this bug only manifests when two column formatted content is present in the Khmer document. Only TN and TQ resource get formatted as two column, so we will only disallow PDF as an output option when either of those resources for Khmer are chosen.
