### ISSUE TITLE
Visual cues to delineate notes from scripture

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/DOC#98]
Aaron Brakefield: Translators felt that there needed to be a clearer break between the source text and the notes, otherwise many translators will end up translating the notes as well. Translators felt a solid line separating and maybe a heading saying "Notes" or even a statement saying, "Do not translate below this line."

**Comment by linearcombination** [comment]
Likely after tomorrow I will be out of approved tasks to work on. If you have ideas for this task and want me to work on it next after the issues already approved, then maybe we could move this into approved too with clarifying comments/suggestions for a first draft, i.e., choose how you want to delineate the end of scripture.

**Comment by abycurley** [comment]
Would like to request that the Translation Notes/Source Text be labelled explicitly so people can recognize what is being referenced if someone references Translation Notes/Source Text.

**Comment by linearcombination** [comment]
@abycurley, @markalolo  Demarcation of USFM from TN content is provided by the TN chapter intros themselves in their title (the very first Markdown headline title), e.g., in English the translators have used the phrase 'Mark 1 General Notes' for TN Mark chapter 1 intro, for example. To change this a translator needs to change the content itself.

Some languages do not currently provide TN chapter intros and in those cases there is no demarcation between USFM and TN content. Presumably at some point translators for those languages will need to provide them and once they do they will be inserted automagically. We do it this way so that the translators can control what is shown and also have it be localized to their language if they so wish.

I hope this makes sense. Please let me know if you have any questions about this.

**Comment by abycurley** [comment]
I think even just inserting a bold line where one resource ends and another begins would be helpful. 

Does your comment mean we'd have to add a comment to each actual repo saying "DO NOT TRANSLATE" or something similar? If so, I don't think that will be a good solution.

**Comment by linearcombination** [comment]
@abycurley I'll add a bold line for starters and if that looks like not enough then we can find other solutions like 'Mark chapter 1 ends here' or 'Translation Notes' (for every language) or ... We can always adjust later.

**Comment by linearcombination** [comment]
Horizontal ruler after each document section has been now implemented for HTML, PDF, and Docx outputs.
