### ISSUE TITLE
Further condensing of notes

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/DOC#99]
Aaron Brakefield: Translators are considering the new proposal of even more condensed notes. They really like the idea of saving paper, but wanted time to see if they feel good about the reductions made in the Galatians example.

Mark Stedman: This is feedback, not an issue to be worked on yet.

**Comment by linearcombination** [comment]
We should show them our existing condensed view, PDF only, and see if they like it or think it is excessively whitespace saving, i.e., see if they think it is too ugly.

**Comment by abycurley** [comment]
I believe Aaron is referring to a separate initiative we're considering in the GL department - the edit down the notes so the content is so overwhelming for printing. The full version of notes would continue to be available electronically, but we're workshopping the content side. In my opinion, this issue can be closed since this new resource offering ("condensed" TN) needs to be produced before it can be integrated into DOC.

**Comment by linearcombination** [comment]
Ok, closing then...
